image: node:latest

pages:
  stage: deploy
  script:
  - echo 'Deploying to GitLab Pages'
  - apt-get update && apt-get install -y git
  - git clone --branch=gh-pages "https://https://gitlab.com/yes132432/foss-web-gaming" public
  - rm -rf public/*
  - cp -r build/* public/
  - cd public
  - git add .
  - git config --global user.email "cassidyaugustlee@gmail.com"
  - git config --global user.name "yes132432"
  - git commit -m "Automated pages deployment"
  - git push origin gh-pages
  artifacts:
    paths:
    - public
  only:
  - master
