# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - git clone https://gitlab.com/yes132432/foss-web-gaming
  - cd foss-web-gaming
  - Install node using your PM
  - test it
  - upload
pages:
  script:
    - Make sure all dependencies are installed
    - Build the production version of your application using a build tool such
      as webpack or gulp
    - The output of the build process will typically be a set of static files
      that can be served by a web server. These files should be minified and
      optimized for production to ensure the best performance.
    - Deploy the built files to a web server or hosting platform.  Verify that
      the production version of your application is running correctly and that
      all features are working as expected.
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH